@echo off
set ANTHROPIC_BASE_URL=http://localhost:20128/v1
set ANTHROPIC_AUTH_TOKEN=sk-0b358a56df3488bf-afac4d-6588c122
set ANTHROPIC_API_KEY=
set ANTHROPIC_MODEL=oc/big-pickle
set ANTHROPIC_SMALL_FAST_MODEL=oc/big-pickle
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
claude %*